apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: lab8-spark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: lab8-spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - name: mongodb
              containerPort: 27017
          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - db.adminCommand('ping').ok
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - db.adminCommand('ping').ok
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "90m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: lab8-spark
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: lab8-spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://mongodb:27017/
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: admin
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: admin
          resources:
            requests:
              cpu: "2m"
              memory: "80Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: lab8-spark
spec:
  type: ClusterIP
  selector:
    app: mongo-express
  ports:
    - name: http
      port: 8081
      targetPort: http
